Configuracion:
    TmpUrl: app/tmp/rutas.php
    ConfigUrl: config/rutas.yml


    Tip: MyT

    versiongestor: 3.1.10
    creado: Did-web.com
    licencia: GPL3
    cliente: WebCliente.com
    webcliente: http://www.webcliente.com
    webcmyt: https://github.com/Didweb/MyT
    webcreador: http://www.did-web.com
    
    idiomas: es
    idiomas_gestor: es
    estilo: img
    
    HOME_dev: http://localhost/MyTDisco/
    HOME: http://www.google.com/
    
    NAMEDB: MyTDisco
    USUARIODB: root
    PASSWORDDB: rasmysql
    
    DirRootDev: /var/www/MyTDisco/
    DirRoot: /xx/xx/xx/
    
    Seguridad: 1

    
    
    
